config/routes.rb
Rails.application.routes.draw do

  get 'students/index'

  get 'sessions', to: 'sessions#new', as: :session_new
  post 'sessions', to: 'sessions#create', as: :session_create
  delete 'logout', to: 'sessions#destroy', as: :delete_session

  get 'users', to: 'users#new', as: :user_new
  post 'users', to: 'users#create', as: :user_create
  get 'users', to: 'users#index' 

  resources "states"
  resources "districts"
  resources "talukas"  


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/district.rb
class District < ApplicationRecord
  has_many :talukas, dependent: :destroy
  belongs_to :state, dependent: :destroy
end

app/models/state.rb
class State < ApplicationRecord
  has_many :districts, dependent: :destroy
  has_many :talukas, dependent: :destroy
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/taluka.rb
class Taluka < ApplicationRecord
  belongs_to :state, dependent: :destroy
  belongs_to :district, dependent: :destroy
end
    

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password_digest_confirmation, presence: true
  validates :password_digest, confirmation: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # helper_method :current_user

  # def authorize
  #   redirect_to users_path, alert: "Not authorized" if current_user.nil?
  # end

  # private
  # def current_user
  #   @current_user || User.find(session[:user_id]) if session[:user_id]
  # end

end

app/controllers/districts_controller.rb
class DistrictsController < ApplicationController
  DISTRICT_PER_PAGE = 3
  def index
    @districts = District.all
    @page = params.fetch(:page, 0).to_i
    @districts = District.limit(DISTRICT_PER_PAGE).offset(@page)
    respond_to do |format|
      format.html
    end 
  end

  def new
    @district = District.new
  end

  def create
    @district = District.new(district_params)
    respond_to do |format|
      if @district.save
        format.js
        format.html {redirect_to districts_path}
      else
        format.js
        format.html {render :new}
      end
    end 
  end

  def edit
    @district = District.find(params[:id])
    respond_to do |format|
      format.js
      format.html 
    end 
  end

  def update
    @district = District.find(params[:id])
    respond_to do |format|
      if @district.update(district_params)
        format.js 
        format.html {redirect_to districts_path}
      else 
        format.js
        format.html {render :edit}
      end
    end
  end

  def destroy
    @district = District.find(params[:id])
    @district.destroy
    respond_to do |format|
      format.js
      format.html {redirect_to districts_path}
    end 
  end

  def show
    @district = District.find(params[:id])
    respond_to do |format|
      format.js
      format.html 
    end 
  end

  private
  def district_params
    params.require(:district).permit(:district_name, :state_id,:taluka_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index
  end 

  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.password_digest == params[:password_digest]
      session[:user_id] = @user.id
      redirect_to states_path
    else
      flash.alert = "Password is incorrect , please check the password"
    
      render "new"
    end  
  end  

  def destroy
    session[:user_id] = nil
    redirect_to users_path, notice: "Logged out!"
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  STATE_PER_PAGE = 3
  def index
    @states = State.all
    @page = params.fetch(:page, 0).to_i
    @states = State.offset(@page * STATE_PER_PAGE).limit(STATE_PER_PAGE)
      respond_to do |format|
      format.html
    end 
  end

  def new
    @state = State.new
  end

  def create
    @state = State.new(state_params)
      respond_to do |format|
      if @state.save
        format.js 
        format.html {redirect_to states_path}
      else
        format.js 
        format.html {render :new}
      end
    end 
  end

  def edit
    @state = State.find(params[:id])
    respond_to do |format|
      format.js
      format.html 
    end
  end

  def update
    @state = State.find(params[:id])
    respond_to do |format|
      if @state.update(state_params)
        format.js
        format.html {redirect_to states_path}
      else 
        format.js 
        format.html {render :edit}
      end 
    end 
  end

  def destroy
    @state = State.find(params[:id])
    @state.destroy
    respond_to do |format|
      format.js
      format.html {redirect_to states_path}
    end 
  end

  def show
    @state = State.find(params[:id])
    respond_to do |format|
      format.js
      format.html
    end
  end

  private
  def state_params
    params.require(:state).permit(:state_name, :district_id, :taluka_id)
  end  
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end
end

app/controllers/talukas_controller.rb
class TalukasController < ApplicationController
  STATE_PER_PAGE = 3
  def index
    @talukas = Taluka.all
    @page = params.fetch(:page, 0).to_i
    @states = State.limit(STATE_PER_PAGE).offset(@page)
    respond_to do |format|
      format.html
    end
  end

  def new
    @taluka = Taluka.new
  end

  def create
    @taluka = Taluka.new(taluka_params)
    respond_to do |format|
      if @taluka.save
        format.js
        format.html {redirect_to talukas_path}
      else
        format.js
        format.html {render :new}
      end 
    end
  end

  def edit
    @taluka = Taluka.find(params[:id])
    respond_to do |format|
      format.js
      format.html 
    end 
  end

  def update
    @taluka = Taluka.find(params[:id])
    respond_to do |format|
      if @taluka.update(taluka_params)
        format.js 
        format.html {redirect_to talukas_path} 
      else 
        format.js 
        format.html {render :edit}
      end 
    end 
  end

  def destroy
    @taluka = Taluka.find(params[:id])
    @taluka.destroy
    respond_to do |format|
      format.js
      format.html {redirect_to talukas_path}
    end 
  end

  def show
    @taluka = Taluka.find(params[:id])
    respond_to do |format|
      format.js
      format.html 
    end 
  end

  private
  def taluka_params
    params.require(:taluka).permit(:name, :district_id, :state_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create 
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to students_index_path
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password_digest, :password_digest_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


  # Returns true if the user is logged in, false otherwise.
    def logged_in?
      !session[:user_id].nil?
    end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/talukas_helper.rb
module TalukasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/districts/_edit.html.erb
<h1>Edit District</h1>

<%= render "form", district: @district %>

app/views/districts/_form.html.erb
<%= form_for @district, remote: true do |form| %>
  <div>
    <%= form.label :district_name %>
    <%= form.text_field :district_name %><br>
  </div>

  <div>
    <%= form.label :state_id %>  
    <%= form.select :state_id, State.all.collect { |p| [p.state_name, p.id] } %><br>
  </div>

  <div>
    <%= form.label :taluka_id %>
    <%= form.select :taluka_id, Taluka.all.collect { |p| [p.name, p.id] } %><br>
  </div>
  <%= form.submit %>
<% end %>

app/views/districts/_row.html.erb
<tr id="district_<%= district.id %>">
<td><%= district.district_name %></td>
<td><%= district.state.state_name %></td>
<td><%=  Taluka.where(id: district.talukas.ids).pluck(:name).join(",") %></td> 
<td> 
  <%= link_to "show", district_path(district.id),method: :get, remote: true, class: "btn btn-outline-warning" %>
  <%= link_to "edit", edit_district_path(district.id), remote: true, class: "btn btn-outline-primary" %>
  <%= link_to "Delete", district_path(district.id), method: :delete, class: "btn btn-outline-danger", remote: true %>
</td>
</tr> 

app/views/districts/_show.html.erb
<h1>District</h1>
district name :- <%= @district.district_name %><br>
state name :- <%= @district.state.state_name %><br>
taluka name :- <%= @district.talukas.name %><br>

app/views/districts/create.js.erb
$("#district").append("<%= j render partial: 'row', locals: { district: @district }%>")
$('#district').html()

app/views/districts/destroy.js.erb
document.getElementById(district_<%= district.id %>").remove();

app/views/districts/edit.js.erb
$('#district_form').html("<%= j (render 'edit') %>"); 
$('#district_form').html()

app/views/districts/index.html.erb
<h1>District</h1>
<table class="table">
  <thead class="thead-dark">
    <th scope="col">District</th>
    <th scope="col">State</th> 
    <th scope="col">Taluka</th> 
    <th scope="col">Action</th>
  </thead>
  <tbody id="district">
    <% @districts.each do |district| %>
      <%= render partial: 'row', locals: { district: district } %>
    <% end %>
  </tbody>
</table>
<%= link_to "Create New Record ", new_district_path, remote: true, class: "btn btn-outline-success" %>
<li><%= link_to "Next page", districts_path(page: @page + 1) %></li>
<li><%= link_to "previous page", districts_path(page: @page - 1) %></li>
<div id="district_form"></div>

app/views/districts/new.html.erb
<h1>New District</h1>
<%= render "form", district: @district %>

app/views/districts/new.js.erb
$('#district_form').html("<%= j (render 'form') %>"); 
$('#district_form').model();

app/views/districts/show.js.erb
$('#district_form').html("<%= j (render 'show') %>");

app/views/districts/update.js.erb
$("#district_<%= district.id %>").replaceWith("<%= j render partial: 'row', locals: { district: @district } %>");
$("#district_form").html();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  </head>
  <body>
  <center>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if logged_in? %>

      <li class="nav-item active">        
        <%= link_to "state", states_path, class: "nav-link active"%>
      </li>

      <li class="nav-item active">        
        <%= link_to "district", districts_path, class: "nav-link active"%>
      </li>  

      <li class="nav-item active">        
        <%= link_to "taluka", talukas_path, class: "nav-link active"%>
      </li>

      <%= link_to "Sign Out", delete_session_path,method: "delete", class: "nav-link active" %>
    <% else %>
      <%= link_to "Sign In", session_new_path %> | 
      <%= link_to "Sign Up", users_path %> <br>

    <% end %>
    </ul>
  </div>
</nav>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
  </center>
  </body>
</html>

app/views/states/_edit.html.erb
<h1> State Edit </h1>

<%= render "form", state: @state %>

  

app/views/states/_form.html.erb
<%= form_with model: @state, remote: true do |form| %>
  <div class="field">
    <%= form.label :state_name %>
    <%= form.text_field :state_name %><br>
  </div>

  <div>
    <%= form.label :district_id %>  
    <%= form.select :district_id, District.all.collect { |p| [p.district_name, p.id] } %><br>
  </div>

<div>
  <%= form.label :taluka_id %>
  <%= form.select :taluka_id, Taluka.all.collect { |p| [p.name, p.id] } %><br>
</div>

  <div class="field">
    <%= form.submit %>
  </div>
  
<% end %>

app/views/states/_row.html.erb
<tr id="state_<%= state.id %>">
  <td><%= state.state_name %></td>
  <td><%=  District.where(id: state.districts.ids).pluck(:district_name).join(",") %></td>
  <td><%=  Taluka.where(id: state.talukas.ids).pluck(:name).join(",") %></td> 
  <td>
    <%= link_to "show", state_path(state.id), method: :get, class: "btn btn-outline-warning", remote: true %>
    <%= link_to "edit", edit_state_path(state.id), method: :get, class: "btn btn-outline-primary", remote: true %>
    <%= link_to "Delete", state_path(state.id), method: :delete, class: "btn btn-outline-danger", remote: true %>
  </td>
</tr>

app/views/states/_show.html.erb
<h1>State</h1>
state name :- <%= @state.state_name %><br>
district name :- <%= @state.districts.name %><br>
taluka name :- <%= @state.talukas.name %>

app/views/states/create.js.erb
$("#state").append("<%= j render partial: 'row', locals: { state: @state }%>")
$('#state').html()

app/views/states/destroy.js.erb
document.getElementById("state_<%= state.id %>").remove();

app/views/states/edit.js.erb
$('#state_form').html("<%= j (render 'form') %>"); 
$('#state_form').html();

app/views/states/index.html.erb
<h1>State</h1>
<table class="table">
  <thead class="thead-dark">
    <th scope="col">State</th>
    <th scope="col">District</th>
    <th scope="col">Taluka</th>
    <th scope="col">Action</th>
  </thead>
  <tbody id="states">
    <% @states.each do |state| %>
      <%= render partial: 'row', locals: {state: state }%>
    <% end %>
  </tbody>
</table>
<%= link_to "Create New Record ", new_state_path, remote: true, class: "btn btn-outline-success" %>
<li><%= link_to "Next page", states_path(page: @page + 1) %></li>
<li><%= link_to "Previous page", states_path(page: @page - 1) %></li>
<div id="state_form"></div>
      

app/views/states/new.html.erb
<h1>New State</h1>
<%= render "form", state: @state %>

app/views/states/new.js.erb
$('#state_form').html("<%= j (render 'form') %>"); 
$('#state_form').model();

app/views/states/show.js.erb
$('#state_form').html("<%= j (render 'show') %>");

app/views/states/update.js.erb
$("#state_<%= state.id %>").replaceWith("<%= j render partial: 'row', locals: { state: @state } %>");
$("#state_form").html();

app/views/talukas/_edit.html.erb
<h1>Edit Taluka</h1>

<%= render "form", taluka: @taluka %>

app/views/talukas/_form.html.erb
<%= form_with model: @taluka, remote: true do |form| %>
  
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %><br>
  </div>

  <div class="field">
    <%= form.label :state_name %>
    <%= form.select :state_id, State.all.map{ |p| [p.state_name, p.id] } %><br>
  </div>

  <div class="field">
    <%= form.label :district_name %>  
    <%= form.select :district_id, District.all.map{ |p| [p.district_name, p.id] } %><br>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/talukas/_row.html.erb
<tr id="taluka <%= taluka.id%>">
  <td><%= taluka.name %></td>
  <td><%= taluka.state.state_name %></td>
  <td><%= taluka.district.district_name %></td>
  <td>
    <%= link_to "show", taluka_path(taluka.id), method: :get, class: "btn btn-outline-warning", remote: true %>
    <%= link_to "edit", edit_taluka_path(taluka.id), method: :get, class: "btn btn-outline-primary", remote: true %>
    <%= link_to "Delete", taluka_path(taluka.id), method: :delete, class: "btn btn-outline-danger", remote: true %>
  </td>
</tr>

app/views/talukas/_show.html.erb
<h1>Taluka</h1>
taluka name :- <%= @taluka.name %><br>
district name :- <%= @taluka.district.district_name %><br>
state name :- <%= @taluka.state.state_name %><br>

app/views/talukas/create.js.erb
$("#taluka").append("<%= j render partial: 'row', locals: { taluka: @taluka }%>")
$('#taluka').html()

app/views/talukas/destroy.js.erb
document.getElementById("taluka_<%= taluka.id %>").remove();

app/views/talukas/edit.js.erb
$('#taluka_form').html("<%= j (render 'edit') %>");
$('#taluka_form').html(); 

app/views/talukas/index.html.erb
<h1>Taluka</h1>
<table class="table">
  <thead class="thead-dark">
    <th scope="col">Name</th> 
    <th scope="col">State</th>
    <th scope="col">District</th> 
    <th scope="col">Action</th>
  </thead>
  <tbody id="taluka">
    <% @talukas.each do |taluka| %>
      <%= render partial: 'row', locals: {taluka: taluka} %>
    <% end %>
  </tbody>
</table>
<%= link_to "Create New Record ", new_taluka_path, remote: true, class: "btn btn-outline-success" %>
<li><%= link_to "Next page", states_path(page: @page + 1) %></li>
<li><%= link_to "Previous page", states_path(page: @page - 1) %></li>
<div id="taluka_form"></div>

app/views/talukas/new.html.erb
<h1>New Taluka</h1>

<%= render "form", taluka: @taluka %>

app/views/talukas/new.js.erb
$('#taluka_form').html("<%= j (render 'form') %>");
$('#taluka_form').model();

app/views/talukas/show.js.erb
$('#taluka_form').html("<%= j (render 'show') %>");

app/views/talukas/update.js.erb
$("#taluka_<%= taluka.id %>").replaceWith("<%= j render partial: 'row', locals: { taluka: @taluka } %>");
$("#taluka_form").html();

app/views/users/index.html.erb
<h1>Hello Dear Friends </h1>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password_digest %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_digest_confirmation %>
  </div>

  <div class="action">
    <%= f.submit "Sign Up" %>
  </div>
<% end %>